name: PunisherX
version: '${version}'
main: pl.syntaxdevteam.PunisherX
api-version: '1.20'
folia-support: true
authors: [SyntaxDevTeam]
description: Advanced punishment system for Minecraft servers with warnings, mutes, bans, kicks and more.
website: https://github.com/SyntaxDevTeam
