name: PunisherX
version: ${version}
description: ${description}
api-version: '1.20'
folia-supported: true

authors: [SyntaxDevTeam]
website: github.com/SyntaxDevTeam/PunisherX
support:
  issues: https://github.com/SyntaxDevTeam/PunisherX/issues
  updates: https://github.com/SyntaxDevTeam/PunisherX/releases

localization:
  available: [en_US, pl_PL, fr_FR, es_ES, de_DE]
  default: en_US

main: pl.syntaxdevteam.punisher.PunisherX
loader: pl.syntaxdevteam.punisher.loader.SyntaxLoader
has-open-classloader: false

softdepend: [Folia]

features:
  debug: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    VaultUnlocked:
      load: BEFORE
      required: false

commands:
  ban:
    description: Bans a player for a specified time with a reason.
    usage: /ban <player> (time) <reason>
    permission: punisherx.cmd.ban
  banip:
    description: Bans a player's IP for a specified time with a reason.
    usage: /banip <ip|player> (time) <reason>
    permission: punisherx.cmd.banip
  unban:
    description: Unbans a player or IP.
    usage: /unban <ip|player>
    permission: punisherx.cmd.unban
  jail:
    description: Allows administrators to jail a player in a specified location in the config.yml for a set duration.
    usage: /jail <player> (time) <reason>
    permission: punisherx.cmd.jail
  unjail:
    description: Counterpart to the jail command. Instantly releases a player from jail, teleporting them to "World Spawn".
    usage: /unjail <player>
    permission: punisherx.cmd.unjail
  setjail:
    description: Sets the jail area with a specified radius. Simply stand at the desired location and use the command to designate the jail area. This simplifies the process, avoiding tedious config settings.
    usage: /unban radius <radius>
    permission: punisherx.cmd.setjail
  setspawn:
    description: Sets the respawn location after a jail sentence ends.
    usage: /setspawn
    permission: punisherx.manage.set_spawn
  mute:
    description: Mutes a player for a specified time with a reason.
    usage: /mute <player> (time) <reason>
    permission: punisherx.cmd.mute
  unmute:
    description: Unmutes a player.
    usage: /unmute <player>
    permission: punisherx.cmd.unmute
  warn:
    description: Issues a warning to a player with an optional duration and reason.
    usage: /warn <player> (time) <reason>
    permission: punisherx.cmd.warn
  unwarn:
    description: Removes the last warning issued to a player.
    usage: /unwarn <player>
    permission: punisherx.cmd.unwarn
  clearall:
    description: Clears all active penalties for a player.
    usage: /clearall <player>
    permission: punisherx.cmd.clearall
  kick:
    description: Kicks a player from the server with a reason.
    usage: /kick <player> <reason>
    permission: punisherx.cmd.kick
  change-reason:
    description: Updates the reason for a specific penalty by ID.
    usage: /change-reason <penalty_id> <new_reason>
    permission: punisherx.cmd.change_reason
  check:
    description: Checks the active penalties for a player.
    usage: /check <player> <warn|mute|ban|all>
    permission: punisherx.check
  history:
    description: Displays the full penalty history for a player.
    usage: /history <player> (page)
    permission: punisherx.cmd.history
  banlist:
    description: Displays a list of banned players with optional history and paging.
    usage: /banlist (--h) (page)
    permission: punisherx.cmd.banlist
  panel:
    description: Opens the PunisherX GUI with useful information and shortcuts.
    usage: /panel
    permission: punisherx.cmd.panel
  langfix:
    description: Converts legacy translation placeholders from {} to <> in the active language file.
    usage: /langfix
    permission: punisherx.cmd.prx
  punisherx:
    aliases: [prx]
    description: Base command for PunisherX with subcommands for help, version, reload, export, import, and migrate.
    usage: /punisherx <help|version|reload|export|import|migrate>
    permission: punisherx.cmd.prx

permissions:
  punisherx.cmd.ban:
    description: Allows banning a player.
    default: op
  punisherx.cmd.banip:
    description: Allows banning a player's IP.
    default: op
  punisherx.cmd.unban:
    description: Allows unbanning a player or IP.
    default: op
  punisherx.cmd.jail:
    description: Allows jailing a player.
    default: op
  punisherx.cmd.unjail:
    description: Allows unjailing a player.
    default: op
  punisherx.manage.set_jail:
    description: Allows setting up a jail.
    default: op
  punisherx.manage.set_spawn:
    description: Allows setting the respawn location after jail.
    default: op
  punisherx.cmd.mute:
    description: Allows muting a player.
  punisherx.cmd.unmute:
    description: Allows unmuting a player.
    default: op
  punisherx.cmd.warn:
    description: Allows issuing a warning to a player.
    default: op
  punisherx.cmd.unwarn:
    description: Allows removing the last warning from a player.
    default: op
  punisherx.cmd.kick:
    description: Allows kicking a player from the server.
    default: op
  punisherx.check:
    description: Allows checking penalties for a player. Not required for self-check.
    default: true
  punisherx.view_ip:
    description: Allows viewing a player's IP in the /check and /history command.
    default: op
  punisherx.cmd.history:
    description: Allows viewing a player's penalty history. Not required for self-check.
    default: true
  punisherx.cmd.banlist:
    description: Allows viewing the list of banned players.
    default: op
  punisherx.cmd.prx:
    description: Allows using the /punisherx and /prx command.
    default: true
  punisherx.cmd.panel:
    description: Allows using the /panel command to open the GUI.
    default: op
  punisherx.manage:
    description: Allows managing the plugin.
    default: op
  punisherx.see:
    description: Allows viewing all punishments.
    default: op
  punisherx.see.ban:
    description: Allows viewing ban notifications.
    default: op
  punisherx.see.banip:
    description: Allows viewing IP ban notifications.
    default: op
  punisherx.see.unban:
    description: Allows viewing unban notifications.
    default: op
  punisherx.see.jail:
    description: Allows viewing jail notifications.
    default: op
  punisherx.see.unjail:
    description: Allows viewing unjail notifications.
    default: op
  punisherx.see.mute:
    description: Allows viewing mute notifications.
    default: op
  punisherx.see.unmute:
    description: Allows viewing unmute notifications.
    default: op
  punisherx.see.warn:
    description: Allows viewing warn notifications.
    default: op
  punisherx.see.unwarn:
    description: Allows viewing unwarn notifications.
    default: op
  punisherx.see.kick:
    description: Allows viewing kick notifications.
    default: op
  punisherx.see.update:
    description: Allows viewing update notifications.
    default: op
  punisherx.bypass:
    description: Allows bypassing all punishments.
    default: false
  punisherx.bypass.warn:
    description: Allows bypassing warnings.
    default: false
  punisherx.bypass.mute:
    description: Allows bypassing mutes.
    default: false
  punisherx.bypass.ban:
    description: Allows bypassing bans.
    default: false
  punisherx.bypass.banip:
    description: Allows bypassing IP bans.
    default: false
  punisherx.bypass.jail:
    description: Allows bypassing jails.
    default: false
  punisherx.bypass.kick:
    description: Allows bypassing kicks.
    default: false
  punisherx.owner:
    description: Allows using all PunisherX commands.
    default: false
  punisherx.cmd.*:
    description: Grants access to all PunisherX commands.
    default: op
  punisherx.manage.*:
    description: Grants access to all management commands.
    default: op
  punisherx.migrate:
    description: Allows migrating the database to another type.
    default: op
  punisherx.see.*:
    description: Allows visibility of various punishment chat notifications.
    default: op
  punisherx.bypass.*:
    description: Prevents punishments from being applied to the user.
    default: false
