name: PunisherX
version: '${version}'
main: pl.syntaxdevteam.punisher.PunisherX
api-version: '1.20'
folia-supported: true
softdepend: [Folia]

authors: [SyntaxDevTeam]
description: Advanced punishment system for Minecraft servers with warnings, mutes, bans, kicks and more.
website: https://github.com/SyntaxDevTeam

load before: [RewarderX]
loader: pl.syntaxdevteam.punisher.loader.SyntaxLoader
has-open-classloader: false